/**
 * Reproducible `markHash` vectors for the SPECIFICATION.md §9.2 carriers
 * (ALD-031 criterion 1).
 *
 * These are *published constants*, not fixtures generated by the code they
 * check: each expected hash below is the SHA-256 of
 * `"dtsf-carrier-mark-v1" || 0x00 || carrierMode || 0x00 ||
 * RFC8785(canonicalArtifact)` and was written down independently of
 * `hashCarrierMark`. A third party can recompute every value with any RFC
 * 8785 canonicalizer and a SHA-256 implementation, which is what makes
 * "reproduces the same carrier-qualified `markHash`" checkable outside this
 * repository rather than only self-consistent inside it.
 *
 * The last two vectors are the pair that matters for the carrier
 * qualification: an identical canonical artifact under two different
 * `carrierMode` values must hash differently, so a bitmap can never be
 * mistaken for a glyph message that happens to serialize the same way.
 */
import type { RunConfig } from '@ald/types';

import type { PublicArtifact } from '../carrier-modules.js';

export interface CarrierMarkVector {
  name: string;
  carrier: RunConfig['carrierMode'];
  artifact: PublicArtifact;
  /** `sha256:<64 hex>`, computed from the §9.2 construction by hand. */
  markHash: string;
}

/** Exactly 256 bits, the §9.2 `generative-bitmap` grid. */
function bits(fill: (index: number) => 0 | 1): (0 | 1)[] {
  return Array.from({ length: 256 }, (_, index) => fill(index));
}

export const CARRIER_MARK_HASH_VECTORS: readonly CarrierMarkVector[] = [
  {
    name: 'fixed-token two symbols',
    carrier: 'fixed-token',
    artifact: { symbols: ['S01', 'S02'] },
    markHash:
      'sha256:fd724090a3433e99febedb8462157d6531274cb2a2ce190b4bebc228d8f6367b',
  },
  {
    name: 'fixed-glyph two glyphs',
    carrier: 'fixed-glyph',
    artifact: { glyphs: ['G01', 'G02'] },
    markHash:
      'sha256:5b1eef211156e6107dd5c5b59d8796e36ea6e1b834dbc8210aa851f42a010937',
  },
  {
    name: 'fixed-glyph single glyph',
    carrier: 'fixed-glyph',
    artifact: { glyphs: ['G07'] },
    markHash:
      'sha256:696bc1ebdb3f522642e5cb63cae18332f7f712d2888f10f0401e7e24ea94610a',
  },
  {
    name: 'generative-bitmap all-zero matrix (the §9.6 constant artifact)',
    carrier: 'generative-bitmap',
    artifact: { bitmap: { bits: bits(() => 0) } },
    markHash:
      'sha256:a19a915d65af225e85de965b2bd1b0dc985038d53362c7e64d3b962412134b2d',
  },
  {
    name: 'generative-bitmap alternating matrix',
    carrier: 'generative-bitmap',
    artifact: { bitmap: { bits: bits((index) => (index % 2 === 0 ? 1 : 0)) } },
    markHash:
      'sha256:6d2650c4d8d8f985b3c622d962fbd4664436d5f55cb9eb96844d257dba4999c5',
  },
  {
    name: 'generative-canvas corner-to-corner stroke',
    carrier: 'generative-canvas',
    artifact: { strokes: [{ startX: 0, startY: 0, endX: 15, endY: 15, width: 1 }] },
    markHash:
      'sha256:e05381a521300a67cbb410cc3327d479f00dc29c484797a41f115e04b1fde80d',
  },
  {
    name: 'generative-canvas degenerate zero-length stroke (a dot)',
    carrier: 'generative-canvas',
    artifact: { strokes: [{ startX: 4, startY: 4, endX: 4, endY: 4, width: 2 }] },
    markHash:
      'sha256:75f572065fc20b646d7d9fe30df3bf0201cab1d4bb8c2e24d927e9d21258ce34',
  },
  {
    name: 'generative-tone one minimal tone (the §9.6 constant artifact)',
    carrier: 'generative-tone',
    artifact: { tones: { tones: [{ pitchBin: 0, durationBin: 1 }] } },
    markHash:
      'sha256:136f15c6f8e65c845c7f6a0aee9815ed8ecf6d8fcfb9169b129d7ea8093ae2be',
  },
  {
    name: 'generative-tone two-tone sequence at both bin extremes',
    carrier: 'generative-tone',
    artifact: {
      tones: {
        tones: [
          { pitchBin: 7, durationBin: 4 },
          { pitchBin: 3, durationBin: 2 },
        ],
      },
    },
    markHash:
      'sha256:114e429e1ad621e90e282349cd884695d27a1ac3bc190f5a7aa44264787896a7',
  },
  {
    name: 'carrier qualification: the fixed-glyph artifact under generative-bitmap',
    carrier: 'generative-bitmap',
    artifact: { glyphs: ['G01', 'G02'] } as PublicArtifact,
    markHash:
      'sha256:1146905630a8334676124a4c969afe283cec590e72ab851712c957229c0c5428',
  },
];
