/**
 * `@ald/gateway` — the Symbol Gateway: the single mediation point for every
 * inter-agent artifact (SPECIFICATION.md §4.1 item 3, §9).
 *
 * There is no route from one Baby to the other. A proposal is validated
 * against the run's registered protocol module, transformed by the §9.6
 * communication-control condition, committed atomically through the one
 * Evidence Writer, and only then released to the receiver. Every rejection is
 * itself evidence and carries a reason code and a payload hash, never the
 * attempted content.
 *
 * Owning backlog items: ALD-029 (core router), ALD-030 (fixed-token
 * protocol), ALD-034 (rejection framework), ALD-035 (boundary schemas),
 * ALD-036 (conformance suite).
 */
export {
  ABSOLUTE_MAX_SYMBOLS_PER_MESSAGE,
  carrierModule,
  DEFAULT_MAX_SYMBOL_REPEATS,
  DEFAULT_MAX_SYMBOLS_PER_MESSAGE,
  fixedTokenModule,
  maxSymbolsFor,
  registerCarrierModule,
  registeredCarriers,
  resetCarrierModules,
  type ActionKind,
  type CarrierContext,
  type CarrierModule,
  type CarrierValidationResult,
  type PublicArtifact,
} from './carrier-modules.js';
export {
  ControlArtifactNotPermittedError,
  GatewayError,
  InterpretationRejectedError,
  InvalidControlArtifactError,
  InvalidSymbolInventoryError,
  isGatewayError,
  OracleRequiresControlArtifactError,
  ShuffledBatchRequiredError,
  toGatewayError,
  toGatewayRejectionResponse,
  TurnDeadlineExceededError,
  UnsupportedCarrierError,
  type GatewayErrorBody,
  type GatewayErrorCode,
  type GatewayErrorResponse,
  type GatewayErrorStatus,
} from './errors.js';
export {
  DEFAULT_COMPLEXITY_BUDGET,
  findTrustedMetadataKey,
  isWithinComplexityBudget,
  PayloadTooComplexError,
  TRUSTED_METADATA_KEYS,
  type ComplexityBudget,
  type TrustedMetadataKey,
} from './inspect.js';
export {
  GATEWAY_REASON_CODES,
  isGatewayReasonCode,
  type GatewayReasonCode,
} from './reason-codes.js';
export {
  GATEWAY_ACTOR_ID,
  MAX_CONSECUTIVE_REJECTIONS_REASON,
  SymbolGatewayImpl,
  withTurnDeadline,
  type GatewayDelivery,
  type GatewayRejection,
  type SymbolGatewayOptions,
} from './symbol-gateway.js';
export {
  assertEveryCarrierHasVectors,
  conformanceVectorsFor,
  registerConformanceVectors,
  resetConformanceVectors,
  CONFORMANCE_INVENTORY,
  CONFORMANCE_MAX_SYMBOL_REPEATS,
  CONFORMANCE_MAX_SYMBOLS,
  conformanceIntentionDraft,
  FIXED_TOKEN_VECTORS,
  type ConformanceVector,
} from './conformance-vectors.js';
export {
  InMemoryEvidenceError,
  InMemoryEvidenceWriter,
  REQUIRED_SIGNER_DOMAINS,
  StepClock,
  type InMemoryEvidenceWriterOptions,
} from './testing.js';
// --- Six-display affect protocol (SPEC §9.3, ALD-033) ----------------------
export {
  AFFECT_ACCEPTED_RESULT_KEYS,
  AFFECT_MEASUREMENT_HASH_DOMAIN,
  AFFECT_REJECTED_RESULT_KEYS,
  AFFECT_VIOLATION_REASON,
  AffectProtocol,
  EMERGENT_AFFECT_ANALYSIS_TAG,
  assertAffectConfiguration,
  normalizedAffectSubmission,
  producesAffectEvents,
  tagEmergentAffect,
  type AffectProtocolHost,
  type AffectRejectionCommit,
  type DerivedAffectRecord,
  type DerivedAffectResult,
  type EmergentAffectTag,
} from './affect.js';
export {
  AffectDisabledError,
  AffectModeMismatchError,
  AffectProtocolError,
  AffectWindowNotOpenError,
  InvalidAffectWindowError,
  InvalidAffectWindowScheduleError,
  UnknownAffectDerivedMappingError,
  type AffectErrorCode,
} from './affect-errors.js';
export {
  AFFECT_DISPLAY_COUNT,
  DEFAULT_AFFECT_DERIVED_MAPPING,
  SUPPORTED_MEASUREMENT_VERSIONS,
  argmaxV1Mapping,
  registerAffectDerivedMapping,
  registeredAffectDerivedMappings,
  resetAffectDerivedMappings,
  resolveAffectDerivedMapping,
  type AffectDerivedMapping,
} from './affect-mapping.js';
export {
  AFFECT_WINDOW_TRIGGER,
  RECOGNISED_AFFECT_WINDOW_SCHEDULES,
  affectActionAvailable,
  affectWindowDue,
  affectWindowFor,
  affectWindowId,
  assertValidAffectWindow,
  createAffectWindow,
  parseAffectWindowSchedule,
  type AffectWindowSchedule,
} from './affect-windows.js';
export {
  AFFECT_NO_SUBMISSION_VECTORS,
  AFFECT_SUBMISSION_MODES,
  AFFECT_VECTOR_NAMESPACE,
  affectVectorKey,
  AFFECT_SUBMISSION_VECTORS,
  AFFECT_VECTOR_MODES,
  affectVectorsFor,
  assertEveryAffectModeHasVectors,
  type AffectVector,
  type AffectVectorMode,
} from './affect-vectors.js';

// ---------------------------------------------------------------------------
// SPEC §9.2 alternate neutral carriers (ALD-031, ALD-032)
// ---------------------------------------------------------------------------
export {
  ABSOLUTE_MAX_STROKES,
  ALTERNATE_CARRIER_MODULES,
  ALTERNATE_CARRIERS,
  BITMAP_BIT_COUNT,
  CARRIER_MARK_HASH_VECTORS,
  BITMAP_GRID_HEIGHT,
  BITMAP_GRID_WIDTH,
  CANVAS_GRID_MAX,
  CANVAS_GRID_MIN,
  CANVAS_STROKE_WIDTHS,
  DEFAULT_MAX_STROKES,
  DEFAULT_SYMBOL_INVENTORY_SIZE,
  GLYPH_AUDIT_REASON_CODES,
  GLYPH_AUDIT_THRESHOLDS,
  GLYPH_AUDIT_VERSION,
  GLYPH_BUNDLE_HASH_DOMAIN,
  GLYPH_BUNDLE_VERSION,
  GLYPH_ID_PATTERN,
  GLYPH_STROKES_MAX,
  GLYPH_STROKES_MIN,
  GlyphBundleAuditFailedError,
  GlyphBundleMismatchError,
  MAX_TONES,
  MissingGlyphBundleHashError,
  TONE_DURATION_BINS,
  TONE_PITCH_BINS,
  UnknownCarrierGrammarError,
  assertGlyphRunConfig,
  assertNoStrings,
  auditGlyphBitmap,
  auditGlyphBundle,
  carrierInventory,
  carrierMarkHash,
  fixedGlyphModule,
  generateGlyphBundle,
  generativeBitmapModule,
  generativeCanvasModule,
  generativeToneModule,
  glyphBitmapFeatures,
  glyphInventory,
  glyphInventoryFor,
  hashGlyphBundle,
  heuristicGlyphLeakageAudit,
  isBit,
  isDurationBin,
  isGlyphBundleHash,
  isGridCoordinate,
  isPitchBin,
  isStrokeWidth,
  isSymbolicCarrier,
  maxStrokesFor,
  randomMarkList,
  readCarrierArtifact,
  readNestedField,
  registerAlternateCarriers,
  validateMarkList,
  verifyGlyphBundle,
  type ArtifactReadResult,
  type AuditableGlyph,
  type CarrierMarkVector,
  type GenerateGlyphBundleOptions,
  type GlyphAuditFinding,
  type GlyphAuditReasonCode,
  type GlyphBitmap,
  type GlyphBitmapFeatures,
  type GlyphBundle,
  type GlyphLeakageAudit,
  type GlyphLeakageAuditResult,
  type MarkListResult,
  type MarkListRules,
} from './carriers/index.js';
export {
  ALL_CARRIER_ACTION_KINDS,
  CARRIER_ACTION_KINDS,
  InvalidCarrierFamilyError,
  assertSingleCarrierFamily,
  availableCarrierActions,
  extraFieldFailure,
  fail,
  isCarrierActionKind,
  trailingRepeats,
  BARE_TOKEN_PATTERN,
} from './carrier-modules.js';
export {
  ALTERNATE_CARRIER_VECTORS,
  CONFORMANCE_GLYPH_INVENTORY,
  FIXED_GLYPH_VECTORS,
  GENERATIVE_BITMAP_VECTORS,
  GENERATIVE_CANVAS_VECTORS,
  GENERATIVE_TONE_VECTORS,
} from './conformance-vectors.js';
